import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>2CIT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="snap-mandatory snap-y">

        {/* hero section */}
        <div id="home" className="w-full h-screen snap-center snap-always " >

        </div>
        {/* hero section */}
        <div id="section1" className="w-full h-screen snap-center snap-always bg-primary-light " >

        </div>
        {/* hero section */}
        <div id="section2" className="w-full h-screen snap-center snap-always " >

        </div>
        {/* hero section */}
        <div id="section3" className="w-full h-screen snap-center snap-always bg-secondary-light " >

        </div>

      </main>
    </>
  )
}
